# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FutureGo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FutureGo
pod 'pop', :git => 'https://github.com/facebook/pop.git'

end
